"""add job fields user_id resume_id requirements jd_summary salary_range location work_type selected_directions

Revision ID: 3941612ef62f
Revises: f67e81431c99
Create Date: 2026-05-14 19:24:35.206150
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3941612ef62f'
down_revision: Union[str, None] = 'f67e81431c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('resume_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('jd_summary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.String(length=256), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(length=256), nullable=True))
    op.add_column('jobs', sa.Column('work_type', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('selected_directions', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_column('jobs', 'selected_directions')
    op.drop_column('jobs', 'work_type')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'jd_summary')
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'resume_id')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
